spring.application.name=food-mood-insights-service

server.port=${PORT:8081}

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=org.postgresql.Driver

logging.level.org.hibernate.persister.entity=ERROR

server.error.whitelabel.enabled=false
server.error.include-message=always
